quote_list = [
            'Nasty in the pasty',
            'Past nastification',
            'Bite my shiny metal ass',
            'Lrrr',
            'Hedonismbot',
            'Robot 1-X',
            'Let me worry about blank',
            'Professor Farnsworth',
            'Planet Express',
            'Boneitis',
            'Zoidberg',
            "We can all fight when we're drunk",
            'Celebrated poopers',
            'Robot 1x',
            'Snu-Snu',
            'Snoo-Snoo',
            'I choose to believe what i was programmed to believe',
            'I dont want to live on this planet anymore',
            'Wernstrom',
            'A fembot living in a manbots manputers world',
            'I find the most erotic part of a woman is the boobies',
            'Shut up and take my money',
            'Sexlexia',
            'Sex-lexia',
            'Zapp Brannigan',
            'Brannigans law',
            'Bender Bending Rodriguez',
            'Cubert Farnsworth',
            'Death to all humans',
            "Please stop sinning while I'm singing",
            'Fing-longer',
            'Finglonger',
            'Hookerbot',
            'Technically correct. The best kind of correct',
            'Once ate a big heaping bowl of salt',
            'Good fundamentals make up for the inability to dunk',
            'You changed the outcome by measuring it',
            'And i have to protect my kids from understanding it',
            'We will not give in to the thinkers',
            'Dr. Banjo',
            'Doctor Banjo', # end lst 1
            'Hubert Farnsworth',
            'Graviolis',
            'Kill all humans',
            'To shreds you say',
            'Bad and you should feel bad',
            'Shut up baby, i know it',
            'My manwich!',
            'My god, a million years',
            'Now strip naked and get on the probulator',
            'With blackjack! And hookers',
            'Turanga Leela',
            'Whalers on the moon',
            'But you are lazy right',
            'Good news, everyone',
            'Smell-o-Scope',
            "Just don't make me smell Uranus",
            'Urectum',
            'Jacking on',
            'Fun on the bun',
            'Mad rhymes with an 80',
            "Captain's itch",
            'The hat goes on the head',
            'Bending college',
            'Robot house',
            'Slurm',
            'Arooo',
            'Omicron Persei 8',
            'Nixon with charisma',
            'Thundercougarfalconbird',
            "Don't quote regulation to me",
            'Why is there yogurt in this cap',
            'Roboamerican studies',
            'Lost city of atlanta',
            'Harpoon my ass',
            'Don-Bot',
            'Donbot',
            'The bourgeois human',
            'Popplers',
            'My precious torso!',
            'You know, I was God once',
            'Plus some other emotions which are weird and deeply confusing',
            'The flesh is spongy and bruised', # end lst 2
            "She's got more meat than a cow",
            'Go man go!',
            "And I'm his friend, Jesus",
            'Philip J. Fry',
            'Hell with your spoiled baby',
            'Build it with 6001 hulls',
            'Kajigger',
            'Hypnotoad',
            'People said I was dumb, but I proved them',
            "That letter that's shaped like a man wearing a hat",
            'Nibblonian',
            'Calculon',
            'Negative, bossy meat creature',
            'My robotic software shall meet your calculatory needs',
            'Homo farnsworth',
            'I guess if you want children beaten, you have to do it yourself',
            'Pabst Blue Robot', 'You were doing well, until everyone died',
            'The device that lets you speed or slow the passage of time',
            'Now all the planets are gonna start cracking wise',
            'Futurella',
            'I moved the stars themselves to write her a love note in the sky',
            'The Scary Door',
            'Your best is an idiot',
            'Earthicans',
            'Let a whole new wave of cruelty wash over this lazy land',
            "Bender, no! You'll make God cry",
            "You can't count on God for jack",
            "When you do things right, people won't be sure you've done anything at all",
            'Ask not for whom the bone bones',
            'EyePhone',
            'Why does Ross, the largest friend, not simply eat the other five',
            'I feel like I was mauled by Jesus',
            'Freedom Day',
            'Smelloscope',
            'I have ridden the mighty moon worm',
            'The devil take this predictable colon',
            'Possibly a dead weasel or a cartoon viewer',
            'Banned after the Star Trek wars',
            'Why am I sticky and naked',
            'Perfectly symmetrical violence never solved anything',
            'Bite my glorious golden ass',
            "Or the Mongooses, that's a good team name", # end lst 3
            'The Fighting Mongooses',
            'Robot Devil',
            'Scooty Puff',
            'If you want a box hurled into the sun, you got to do it yourself',
            "Thanks, dad. I think I'll invest it on five shares of Amazon",
            "I never thought I'd escape with my doodle, but I pulled it out",
            'Looks like you get to hold onto your lower horn',
            'Human horn',
            'That could be my beautiful soul sitting naked on her couch',
            'Rodger your Hammerstein',
            "I can't believe the devil is so unforgiving",
            "I haven't felt much of anything since my guinea pig died",
            'Hide in this barrel, like the wily fish',
            "I don't like the looks of this V-GINY",
            "V-GINY? Doesn't ring a bell",
            "We're next if we don't keep in in our collective pants",
            'The only lies worth believing are the ones in the Bible',
            'Einstein is a hard name to remember',
            "I'll be a monkey's uncle if I'm this monkey's nephew",
            'What the hoth',
            'Robanukah',
            'Liubot',
            'Anything less than immortality is a complete waste of time',
            'The candle that burns twice as bright burns half as long. Mmm-hmm',
            'Probably some hogwash about the human spirit',
            "Time? I can't go back there",
            'Sell your extra bones for cash',
            'Mobius dick',
            "Something sinister won't build itself",
            'Evolve from filthy monkey-men',
            'Like the deadly Prius',
            'Give us back our genitals',
            'Never bet against me being stupid',
            'All that and a small wiener',
            "We've opened Pandora's fly",
            'Except for Drugman',
            'Think you can just waltz in here with no pants and become a cop',
            'What a stupid, phony, made up name',
            'Mr. Peppy',
            'Why, I used to smoke about four feet of rope a day',
            'I hate the people that love me, and they hate me',
            'Blernsball', # end lst 4
            'Be a prude fry',
            "I'm so embarrassed.  I wish everyone else was dead",
            "Nature's pocket",
            'I can eat. and fertilize',
            'Have the boy lay out my formal shorts',
            'I both rue and lament it',
            'These balls are making me testy',
            'Body bags and ball sacs',
            'War were declared',
            'Pimpmobile',
            'Fatbot',
            'Ask Wingus and Dingus',
            'You ever kill a man with a sock',
            'Werecar',
            'What smells like blue',
            'Looks like fun on a bun',
            'Please insert girder',
            'Hobo and a rabbit',
            'Robo-american studies',
            'Councel of robot elders',
            'Robot Santa',
            'Ndnd',
            'Borax kid',
            "56?! Now that's all I can think about",
            'If you want a box hurled into the sun you got to do it yourself',
            'Space Pope',
]
# 'Futurama', 'nibbler', 'morbo', 'meatbag', 'gender bender', 'suicide booth', 'leela', 'space pope', 'Oh, dip!', 'death by snu', 'Why not Zoidberg', ]
